language: rust
cache: cargo
os:
  - osx
  - linux
rust:
  - stable
  - beta

script:
  - cargo install alice-download --force
  - alice-download 1
  - cargo clean
  - rustup component add rustfmt clippy
  - cargo +$TRAVIS_RUST_VERSION clippy
  - cargo +$TRAVIS_RUST_VERSION fmt  -p alice-download -- --check
  - cargo +$TRAVIS_RUST_VERSION fmt  -p alice-open-data -- --check
  - cargo +$TRAVIS_RUST_VERSION fmt  -p malice -- --check
  - cargo +$TRAVIS_RUST_VERSION fmt  -p root-ls -- --check
  - cargo +$TRAVIS_RUST_VERSION fmt  -p histogram -- --check
  - cargo +$TRAVIS_RUST_VERSION fmt  -p simple-analysis -- --check
  - cargo +$TRAVIS_RUST_VERSION fmt  -p convert_to_msgpack -- --check
  - cargo build --verbose --all --release
  - cargo test --verbose --all --release
