language: rust
os:
  - linux
  - osx
  - windows
rust:
  - stable
  - beta

before_install:
  - rustup component add rustfmt clippy

script:
  - cargo +$TRAVIS_RUST_VERSION fmt -- --check
  - cargo +$TRAVIS_RUST_VERSION clippy
  - cargo build --verbose --all
  # We need to download some files before we can run the tests.
  - cd alice-download && cargo run -- 1 && cd ..  
  - cargo test --verbose --all
