[workspace]
members = [
 "alice-download",
 "alice-open-data",
 "histogram",
 "root-io",
 "root-ls",
 "track-dca-sys",
 "malice",
 "examples/simple-analysis",
 "examples/convert_to_msgpack",
 "examples/invariant_mass",
]
