[workspace]
members = [
 "alice-download",
 "alice-open-data",
 "histogram",
 "root-io",
 "root-ls",
 "malice",
 "examples/simple-analysis",
 "examples/convert_to_msgpack",
]

[workspace.dependencies]
nom = "^7"
reqwest = "0.11"
