[package]
name = "histogram"
version = "0.1.0"
authors = ["cbourjau <c.bourjau@posteo.de>"]

[dependencies]
ndarray = {version="^0.13", features = ["serde-1"]}
itertools = "^0.8.2"
serde = "1.0.27"
num-traits = "^0.1"
bincode = "1.0.0"
failure = "0.1.1"
