[package]
name = "histogram"
version = "0.1.0"
authors = ["cbourjau <c.bourjau@posteo.de>"]
edition = "2018"

[dependencies]
bincode = "1.0.0"
failure = "0.1.1"
ndarray = {version="^0.13", features = ["serde-1"]}
wasm-bindgen = "0.2.62"
