[package]
name = "alice-open-data"
version = "0.2.1"
authors = ["cbourjau <c.bourjau@posteo.de>"]
description = "Tools to download and manage the publicly released ALICE open data"
repository = "https://github.com/cbourjau/alice-rs"
readme = "README.md"
keywords = ["cern", "alice", "lhc", "physics", "data"]
categories = ["science"]
license = "MPL-2.0"


[dependencies]
glob = "^0.2.11"
failure = "0.1.1"
reqwest = {"version"= "0.10.0-alpha.1", "features"=["blocking"]}
futures-preview = { version = "0.3.0-alpha.14"}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dirs = "1.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.2"
