[package]
name = "convert_to_msgpack"
version = "0.1.0"
authors = ["cbourjau <c.bourjau@posteo.de>"]
edition = "2018"

[dependencies]
alice-open-data = "0.3.0"
malice = "0.2.1"
rmp-serde = "0.13.7"
root-io = "0.2.1"
serde = "1.0"
serde_derive = "1.0"
