[package]
name = "simple-analysis"
version = "0.1.0"
authors = ["cbourjau <c.bourjau@posteo.de>"]
workspace = "../../"
edition = "2018"

[dependencies]
malice = "0.1.1"
root-io = "0.1.1"
alice-open-data = "0.2.0"
gnuplot = "^0.0.22"
histogram = {path = "../../histogram" }
failure = "0.1.1"
