/********************************************************************
* G__ESD.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G__ESD.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__ESD();
extern void G__cpp_setup_inheritanceG__ESD();
extern void G__cpp_setup_typetableG__ESD();
extern void G__cpp_setup_memvarG__ESD();
extern void G__cpp_setup_globalG__ESD();
extern void G__cpp_setup_memfuncG__ESD();
extern void G__cpp_setup_funcG__ESD();
extern void G__set_cpp_environmentG__ESD();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "AliCascadeVertexer.h"
#include "AliESDACORDE.h"
#include "AliESDAD.h"
#include "AliESDADfriend.h"
#include "AliESDCaloCells.h"
#include "AliESDCaloCluster.h"
#include "AliESDCaloTrigger.h"
#include "AliESDcascade.h"
#include "AliESDCosmicTrack.h"
#include "AliESD.h"
#include "AliESDEvent.h"
#include "AliESDFIT.h"
#include "AliESDFMD.h"
#include "AliESDfriend.h"
#include "AliESDfriendTrack.h"
#include "AliESDHandler.h"
#include "AliESDHeader.h"
#include "AliESDHLTDecision.h"
#include "AliESDHLTtrack.h"
#include "AliESDInputHandler.h"
#include "AliESDInputHandlerRP.h"
#include "AliESDkink.h"
#include "AliESDMultITS.h"
#include "AliESDMuonCluster.h"
#include "AliESDMuonGlobalTrack.h"
#include "AliESDMuonPad.h"
#include "AliESDMuonTrack.h"
#include "AliESDpid.h"
#include "AliESDPmdTrack.h"
#include "AliESDRun.h"
#include "AliESDTOFCluster.h"
#include "AliESDTOFHit.h"
#include "AliESDTOFMatch.h"
#include "AliESDtrack.h"
#include "AliESDTrdTrack.h"
#include "AliESDTrdTracklet.h"
#include "AliESDTrdTrigger.h"
#include "AliESDTZERO.h"
#include "AliESDTZEROfriend.h"
#include "AliESDUtils.h"
#include "AliESDv0.h"
#include "AliESDV0Params.h"
#include "AliESDVertex.h"
#include "AliESDVZERO.h"
#include "AliESDVZEROfriend.h"
#include "AliESDZDC.h"
#include "AliExpression.h"
#include "AliFMDFloatMap.h"
#include "AliFMDMap.h"
#include "AliKalmanTrack.h"
#include "AliKFParticleBase.h"
#include "AliKFParticle.h"
#include "AliKFVertex.h"
#include "AliMeanVertex.h"
#include "AliMultiplicity.h"
#include "AliRawDataErrorLog.h"
#include "AliSelector.h"
#include "AliStrLine.h"
#include "AliTrackerBase.h"
#include "AliTrackPointArray.h"
#include "AliTriggerBCMask.h"
#include "AliTriggerClass.h"
#include "AliTriggerCluster.h"
#include "AliTriggerConfiguration.h"
#include "AliTriggerDescriptor.h"
#include "AliTriggerInput.h"
#include "AliTriggerInteraction.h"
#include "AliTriggerIR.h"
#include "AliTriggerPFProtection.h"
#include "AliTriggerScalersESD.h"
#include "AliTriggerScalersRecordESD.h"
#include "AliV0vertexer.h"
#include "AliVertex.h"
#include "AliVertexerTracks.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__ESDLN_TClass;
extern G__linked_taginfo G__G__ESDLN_TBuffer;
extern G__linked_taginfo G__G__ESDLN_TMemberInspector;
extern G__linked_taginfo G__G__ESDLN_TObject;
extern G__linked_taginfo G__G__ESDLN_TNamed;
extern G__linked_taginfo G__G__ESDLN_TString;
extern G__linked_taginfo G__G__ESDLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__ESDLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ESDLN_TList;
extern G__linked_taginfo G__G__ESDLN_TObjArray;
extern G__linked_taginfo G__G__ESDLN_TClonesArray;
extern G__linked_taginfo G__G__ESDLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__ESDLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ESDLN_AliESDEvent;
extern G__linked_taginfo G__G__ESDLN_AliESDv0;
extern G__linked_taginfo G__G__ESDLN_AliExternalTrackParam;
extern G__linked_taginfo G__G__ESDLN_AliCascadeVertexer;
extern G__linked_taginfo G__G__ESDLN_AliESDACORDE;
extern G__linked_taginfo G__G__ESDLN_AliVAD;
extern G__linked_taginfo G__G__ESDLN_AliVADcLcLDecision;
extern G__linked_taginfo G__G__ESDLN_AliESDAD;
extern G__linked_taginfo G__G__ESDLN_AliESDADfriend;
extern G__linked_taginfo G__G__ESDLN_AliESDADfriendcLcLEESDADfriendParams;
extern G__linked_taginfo G__G__ESDLN_AliVCaloCells;
extern G__linked_taginfo G__G__ESDLN_AliVCaloCellscLcLVCells_t;
extern G__linked_taginfo G__G__ESDLN_AliESDCaloCells;
extern G__linked_taginfo G__G__ESDLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__G__ESDLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__ESDLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__ESDLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__G__ESDLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__G__ESDLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__G__ESDLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__G__ESDLN_TVector3;
extern G__linked_taginfo G__G__ESDLN_TLorentzVector;
extern G__linked_taginfo G__G__ESDLN_AliVCluster;
extern G__linked_taginfo G__G__ESDLN_AliVClustercLcLVCluUserDefEnergy_t;
extern G__linked_taginfo G__G__ESDLN_AliPID;
extern G__linked_taginfo G__G__ESDLN_AliPIDcLcLEParticleType;
extern G__linked_taginfo G__G__ESDLN_TArrayI;
extern G__linked_taginfo G__G__ESDLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__ESDLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__G__ESDLN_AliESDCaloCluster;
extern G__linked_taginfo G__G__ESDLN_AliVCaloTrigger;
extern G__linked_taginfo G__G__ESDLN_AliESDCaloTrigger;
extern G__linked_taginfo G__G__ESDLN_TBits;
extern G__linked_taginfo G__G__ESDLN_AliVParticle;
extern G__linked_taginfo G__G__ESDLN_AliVEvent;
extern G__linked_taginfo G__G__ESDLN_AliVVertex;
extern G__linked_taginfo G__G__ESDLN_AliESDVertex;
extern G__linked_taginfo G__G__ESDLN_AliTPCdEdxInfo;
extern G__linked_taginfo G__G__ESDLN_AliDetectorPID;
extern G__linked_taginfo G__G__ESDLN_AliTOFHeader;
extern G__linked_taginfo G__G__ESDLN_AliVTrack;
extern G__linked_taginfo G__G__ESDLN_TPolyMarker3D;
extern G__linked_taginfo G__G__ESDLN_AliESDV0Params;
extern G__linked_taginfo G__G__ESDLN_AliESDcascade;
extern G__linked_taginfo G__G__ESDLN_AliESDCosmicTrack;
extern G__linked_taginfo G__G__ESDLN_TArrayF;
extern G__linked_taginfo G__G__ESDLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__G__ESDLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__G__ESDLN_AliESDMuonTrack;
extern G__linked_taginfo G__G__ESDLN_AliESDMuonTrackcLcLEAliTriggerChPatternFlag;
extern G__linked_taginfo G__G__ESDLN_AliESDMuonTrackcLcLEAliTriggerChPatternInfo;
extern G__linked_taginfo G__G__ESDLN_AliESDPmdTrack;
extern G__linked_taginfo G__G__ESDLN_TFile;
extern G__linked_taginfo G__G__ESDLN_TRef;
extern G__linked_taginfo G__G__ESDLN_AliVTrdTracklet;
extern G__linked_taginfo G__G__ESDLN_AliVTrdTrack;
extern G__linked_taginfo G__G__ESDLN_AliESDTrdTracklet;
extern G__linked_taginfo G__G__ESDLN_AliVTOFcluster;
extern G__linked_taginfo G__G__ESDLN_AliVTOFHit;
extern G__linked_taginfo G__G__ESDLN_AliESDTOFHit;
extern G__linked_taginfo G__G__ESDLN_AliVTOFMatch;
extern G__linked_taginfo G__G__ESDLN_AliESDTOFMatch;
extern G__linked_taginfo G__G__ESDLN_AliESDTOFCluster;
extern G__linked_taginfo G__G__ESDLN_AliTPCseed;
extern G__linked_taginfo G__G__ESDLN_AliTrackPointArray;
extern G__linked_taginfo G__G__ESDLN_AliVfriendTrack;
extern G__linked_taginfo G__G__ESDLN_TGeoRotation;
extern G__linked_taginfo G__G__ESDLN_AliTrackPoint;
extern G__linked_taginfo G__G__ESDLN_AliTrackPointArraycLcLdA;
extern G__linked_taginfo G__G__ESDLN_AliKalmanTrack;
extern G__linked_taginfo G__G__ESDLN_AliESDfriendTrack;
extern G__linked_taginfo G__G__ESDLN_AliESDfriendTrackcLcLdA;
extern G__linked_taginfo G__G__ESDLN_TParticle;
extern G__linked_taginfo G__G__ESDLN_TTreeSRedirector;
extern G__linked_taginfo G__G__ESDLN_AliESDtrack;
extern G__linked_taginfo G__G__ESDLN_AliESDtrackcLcLdA;
extern G__linked_taginfo G__G__ESDLN_AliESDTrdTrack;
extern G__linked_taginfo G__G__ESDLN_AliVertex;
extern G__linked_taginfo G__G__ESDLN_AliESDkink;
extern G__linked_taginfo G__G__ESDLN_AliESDHLTtrack;
extern G__linked_taginfo G__G__ESDLN_AliFMDMap;
extern G__linked_taginfo G__G__ESDLN_AliFMDMapcLcLdA;
extern G__linked_taginfo G__G__ESDLN_AliFMDMapcLcLForOne;
extern G__linked_taginfo G__G__ESDLN_AliFMDFloatMap;
extern G__linked_taginfo G__G__ESDLN_AliESDFMD;
extern G__linked_taginfo G__G__ESDLN_AliESDFMDcLcLForOne;
extern G__linked_taginfo G__G__ESDLN_AliESDFMDcLcLdA;
extern G__linked_taginfo G__G__ESDLN_AliVVZERO;
extern G__linked_taginfo G__G__ESDLN_AliVVZEROcLcLDecision;
extern G__linked_taginfo G__G__ESDLN_AliESDVZERO;
extern G__linked_taginfo G__G__ESDLN_AliVMultiplicity;
extern G__linked_taginfo G__G__ESDLN_AliRefArray;
extern G__linked_taginfo G__G__ESDLN_AliMultiplicity;
extern G__linked_taginfo G__G__ESDLN_AliRawDataErrorLog;
extern G__linked_taginfo G__G__ESDLN_AliRawDataErrorLogcLcLERawDataErrorLevel;
extern G__linked_taginfo G__G__ESDLN_AliESDfriend;
extern G__linked_taginfo G__G__ESDLN_AliESD;
extern G__linked_taginfo G__G__ESDLN_TTree;
extern G__linked_taginfo G__G__ESDLN_TSelector;
extern G__linked_taginfo G__G__ESDLN_TGeoHMatrix;
extern G__linked_taginfo G__G__ESDLN_AliVHeader;
extern G__linked_taginfo G__G__ESDLN_TRefArray;
extern G__linked_taginfo G__G__ESDLN_AliVfriendEvent;
extern G__linked_taginfo G__G__ESDLN_AliCentrality;
extern G__linked_taginfo G__G__ESDLN_AliEventplane;
extern G__linked_taginfo G__G__ESDLN_AliVZDC;
extern G__linked_taginfo G__G__ESDLN_AliVEventcLcLEDataLayoutType;
extern G__linked_taginfo G__G__ESDLN_AliTimeStamp;
extern G__linked_taginfo G__G__ESDLN_AliESDRun;
extern G__linked_taginfo G__G__ESDLN_AliESDRuncLcLStatusBits;
extern G__linked_taginfo G__G__ESDLN_AliESDRuncLcLdA;
extern G__linked_taginfo G__G__ESDLN_AliTriggerScalersESD;
extern G__linked_taginfo G__G__ESDLN_AliTriggerScalersRecordESD;
extern G__linked_taginfo G__G__ESDLN_AliTriggerIR;
extern G__linked_taginfo G__G__ESDLN_AliTriggerConfiguration;
extern G__linked_taginfo G__G__ESDLN_AliESDHeader;
extern G__linked_taginfo G__G__ESDLN_AliESDHeadercLcLdA;
extern G__linked_taginfo G__G__ESDLN_AliESDTZERO;
extern G__linked_taginfo G__G__ESDLN_AliESDFIT;
extern G__linked_taginfo G__G__ESDLN_AliESDZDC;
extern G__linked_taginfo G__G__ESDLN_AliVVZEROfriend;
extern G__linked_taginfo G__G__ESDLN_AliESDVZEROfriend;
extern G__linked_taginfo G__G__ESDLN_AliESDTZEROfriend;
extern G__linked_taginfo G__G__ESDLN_AliESDTrdTrigger;
extern G__linked_taginfo G__G__ESDLN_AliESDMuonCluster;
extern G__linked_taginfo G__G__ESDLN_AliESDMuonPad;
extern G__linked_taginfo G__G__ESDLN_AliESDMuonGlobalTrack;
extern G__linked_taginfo G__G__ESDLN_AliESDHLTDecision;
extern G__linked_taginfo G__G__ESDLN_AliESDEventcLcLESDListIndex;
extern G__linked_taginfo G__G__ESDLN_AliVEventHandler;
extern G__linked_taginfo G__G__ESDLN_AliESDHandler;
extern G__linked_taginfo G__G__ESDLN_TArrayL64;
extern G__linked_taginfo G__G__ESDLN_AliESDHLTDecisioncLcLdA;
extern G__linked_taginfo G__G__ESDLN_AliRunTag;
extern G__linked_taginfo G__G__ESDLN_AliEventTag;
extern G__linked_taginfo G__G__ESDLN_AliPIDResponse;
extern G__linked_taginfo G__G__ESDLN_AliInputEventHandler;
extern G__linked_taginfo G__G__ESDLN_TChain;
extern G__linked_taginfo G__G__ESDLN_TMap;
extern G__linked_taginfo G__G__ESDLN_AliESDpid;
extern G__linked_taginfo G__G__ESDLN_AliESDInputHandler;
extern G__linked_taginfo G__G__ESDLN_TDirectoryFile;
extern G__linked_taginfo G__G__ESDLN_AliESDInputHandlerRP;
extern G__linked_taginfo G__G__ESDLN_AliESDInputHandlerRPcLcLdA;
extern G__linked_taginfo G__G__ESDLN_AliESDMultITS;
extern G__linked_taginfo G__G__ESDLN_AliVertexerTracks;
extern G__linked_taginfo G__G__ESDLN_AliESDUtils;
extern G__linked_taginfo G__G__ESDLN_AliExpression;
extern G__linked_taginfo G__G__ESDLN_AliVariableExpression;
extern G__linked_taginfo G__G__ESDLN_AliCluster;
extern G__linked_taginfo G__G__ESDLN_AliKFParticleBase;
extern G__linked_taginfo G__G__ESDLN_AliKFParticle;
extern G__linked_taginfo G__G__ESDLN_AliKFVertex;
extern G__linked_taginfo G__G__ESDLN_AliMeanVertex;
extern G__linked_taginfo G__G__ESDLN_AliSelector;
extern G__linked_taginfo G__G__ESDLN_AliStrLine;
extern G__linked_taginfo G__G__ESDLN_AliTrackerBase;
extern G__linked_taginfo G__G__ESDLN_AliTriggerBCMask;
extern G__linked_taginfo G__G__ESDLN_AliTriggerBCMaskcLcLdA;
extern G__linked_taginfo G__G__ESDLN_AliTriggerDescriptor;
extern G__linked_taginfo G__G__ESDLN_AliTriggerCluster;
extern G__linked_taginfo G__G__ESDLN_AliTriggerPFProtection;
extern G__linked_taginfo G__G__ESDLN_AliTriggerClass;
extern G__linked_taginfo G__G__ESDLN_AliTriggerClasscLcLdA;
extern G__linked_taginfo G__G__ESDLN_AliTriggerInput;
extern G__linked_taginfo G__G__ESDLN_AliTriggerInteraction;
extern G__linked_taginfo G__G__ESDLN_AliTriggerConfigurationcLcLdA;
extern G__linked_taginfo G__G__ESDLN_AliV0vertexer;
extern G__linked_taginfo G__G__ESDLN_AliVertexerTrackscLcLdA;

/* STUB derived class for protected member access */
