[package]
name = "root-io"
version = "0.1.2"
authors = ["cbourjau <c.bourjau@posteo.de>"]
exclude = ["*test_data/", "*.root"]
description = "Reading of `.root` binary files which are commonly used in particle physics"
repository = "https://github.com/cbourjau/alice-rs"
readme = "README.md"
keywords = ["root", "cern", "alice", "lhc", "physics"]
categories = ["parser-implementations", "science", "data-structures"]
license = "MPL-2.0"


[dependencies]
alice-open-data = {"path"= "../alice-open-data"}
flate2 = "^1"
bitflags = "1.0.0"
quote = "0.3.15"
failure = "0.1.5"
reqwest = {"version"="0.10.0-alpha.1", "features"=["blocking"]}
lzma-rs = "0.1.1"

[dependencies.nom]
version = "^3"
features = [] # avoid the default memchar feature for wasm's sake

[dev-dependencies]
criterion = "0.3"

# Run with cargo bench --bench iter_branch -- --baseline pathbuf-in-container --color never
[[bench]]
name = "iter_branch"
harness = false
