[package]
name = "root-io"
version = "0.1.2"
authors = ["cbourjau <c.bourjau@posteo.de>"]
exclude = ["*test_data/", "*.root"]
description = "Reading of `.root` binary files which are commonly used in particle physics"
repository = "https://github.com/cbourjau/alice-rs"
readme = "README.md"
keywords = ["root", "cern", "alice", "lhc", "physics"]
categories = ["parser-implementations", "science", "data-structures"]
license = "MPL-2.0"
edition = "2018"


[dependencies]
alice-open-data = {"path"= "../alice-open-data"}
flate2 = "^1"
bitflags = "1.0.0"
quote = "0.3.15"
failure = "0.1.5"
reqwest = {"path"="../../reqwest"}
lzma-rs = "0.1.1"
async-trait = "0.1.17"
futures-preview = "=0.3.0-alpha.19"

[dependencies.nom]
version = "^5"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = "0.2.0-alpha.6"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.3"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
criterion = "0.3"
tokio = "0.2.0-alpha.6"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.3"
wasm-bindgen = "0.2.53"
web-sys = {"version" = "0.3.4", "features" = [ 'console' ]}

# Run with cargo bench --bench iter_branch -- --baseline pathbuf-in-container --color never
[[bench]]
name = "iter_branch"
harness = false

