name: test suite
on: [push]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - run: cargo clippy
      - run: cargo fmt -- --check
      - run: cargo run --bin alice-download --release -- 1
      - run: cargo test --all-features
        env:
          RUST_BACKTRACE: 1
  wasm:
    name: build wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - run: cargo build -p malice --target wasm32-unknown-unknown
